version: "3"
services:
  app:
    build: .
    ports:
      - "6062:6062"
    depends_on:
      - db
    volumes:
       - .:/app:z
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spamdb
