version: "3"
services:
    postgresdb:
        image: postgres:14.9-alpine3.18
        restart: always
        container_name: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: spamapp
        # ports:
        #     - "5433:5432"
        volumes:
            - db:/var/lib/postgresql/data
    app:
        image: hiijitesh/spam-blocker:latest
        container_name: spam-app
        build: .
        ports:
            - "6500:6500"
        depends_on:
            - postgresdb
        environment:
            # NODE_ENV: production
            DB_HOST: postgresdb
            DB_PORT: 5432
            DATABASE_USER_NAME: postgres
            DATABASE_PASSWORD: postgres
            DATABASE_NAME: spamapp
        volumes:
            - .:/app:z

volumes:
    db:
        driver: local
